azs:
- name: z1
  cloud_properties:
    availability_zone: nova

vm_type_defaults: &vm_type_defaults
  az: z1
  cloud_properties:
    instance_type: m1.lite

vm_types:
- name: default
  <<: *vm_type_defaults
- name: web
  <<: *vm_type_defaults
- name: database
  <<: *vm_type_defaults
- name: worker
  <<: *vm_type_defaults

disk_types:
- name: default
  disk_size: 2_000
- name: database
  disk_size: 2_000

networks:
- name: private
  type: dynamic
  subnets:
  - cloud_properties: {net_id: 10ec8e04-eb63-411b-9fee-947b3a4ebf09} # <--- # Replace with private network UUID
    az: z1
- name: public
  type: vip
  az: z1

compilation:
  workers: 1
  reuse_compilation_vms: true
  network: private
  <<: *vm_type_defaults

